### ISSUE TITLE
Error on page read, when field is present but empty

### ISSUE THREAD

**Issue by cafterh** [Andful/netlify-cms-widget-create-select#4]
In some of my markdown files with frontmatter, I created them before netlify-cms with a template consisting of all usable fields being present but blank. I am using this widget to adjust a `tags:` list that has no entries yet, and upon opening the post edit page, I receive an error:
```
TypeError: e is null
Source: render, https://unpkg.com/netlify-cms-widget-create-select@^1.1.0:10
```
I believe this is from an unhandled exception to an empty read of that field.

**Comment by Andful** [comment]
Thank you for filing a pull request. The commit 87df5cfa69ded123184670f00f581dc7ee36bbcb should have fixed the issue.

**Comment by cafterh** [comment]
Great, but now I'm getting a strange interaction with my preview template (once again only when there is an empty list field)

I don't know too much about React, but in a custom class which has been registered as a preview template, I am calling `this.props.entry(["data", "FIELDNAME"], [])`, Every other widget, if unsuccessful or empty, uses that empty array as null fallback.

With your widget, upon an empty list field an error is still thrown `entry.getIn(...) is null`

I have fixed this by wrapping the function call in another fallback but I though you should know. 

My temporary fix: `(this.props.entry(["data", "FIELDNAME"], []) || [])`

**Comment by Andful** [comment]
I will have a look on this.

**Comment by Andful** [comment]
Do you have a minimal working example?

**Comment by cafterh** [comment]
Please disregard! I couldn't make this error repeatable reliably and its not isolated to this widget either. Thanks for your assistance!

**Comment by Andful** [comment]
I did a major refactor in version in 1.1.5 also aiming to solve the problem you gave. I think you not being able to reproduce it is a sign of it being fixed. Thank you for the issue.
