### ISSUE TITLE
Local Backend - CORS error means always loading, no manual entry/create

### ISSUE THREAD

**Issue by cafterh** [Andful/netlify-cms-widget-create-select#6]
Last Issue today, this one is less pressing because I know it works on production servers just not localhost/127.0.0.1

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at <URL>. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
```

I'm using the netlify-cms-proxy-server and `local_backend` option, and getting this error. This is normal CORS limitation, but the uncaught error means that the widget displays "Loading" forever, and the create functionality doesn't work. I think it would be a good alternative to have it catch the failed html scraping and still allow you to manually enter values.

Thank you for your prompt work on this today!

**Comment by Andful** [comment]
Good point. I will work on this.

**Comment by Andful** [comment]
Now you should be able to insert entries even when an error occurs. Also it shows what error occurred when there are no options due to error. You can check the changes on version 1.1.4. Thank you for beta testing and actually making this library usable.
